version: "3.0"
services:
  database:
    image: mongo:latest
  app:
    image: spaceapi-radar/push-server
    build: .
    depends_on:
      - database
    ports:
      - 8080:8080
  gui:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - database
    environment:
      - ME_CONFIG_MONGODB_SERVER=database