version: 2
jobs:
 build:
   docker:
    - image: docker:stable
   steps:
    - setup_remote_docker
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t spaceradar/push-server .
    - run: |
        docker tag spaceradar/push-server spaceradar/push-server:$CIRCLE_SHA1
        docker push spaceradar/push-server:$CIRCLE_SHA1
        docker push spaceradar/push-server:latest
